variables:
  GIT_SUBMODULE_STRATEGY: normal

before_script:
  - export PATH=/opt/lm32-gcc-4.5.3/bin:$PATH

stages:
- compile

make_wrpc_sw:
  stage: compile
  tags:
    - wrs_sw
  script:
  - make spec_defconfig
  - make
  artifacts:
    name: WRPC_SW_CI_%CI_JOB_ID%
    paths:
    - wrc.bin
    - wrc.elf
    - wrc.bram
    - wrc.mif

make_spec7:
  stage: compile
  tags:
    - wrs_sw
  script:
  - make spec7_defconfig
  - make
  artifacts:
    name: WRPC_SW_CI_%CI_JOB_ID%
    paths:
    - wrc.bin
    - wrc.elf
    - wrc.bram
    - wrc.mif

make_rt_cpu:
  stage: compile
  tags:
    - wrs_sw
  script:
  - make wr_switch_defconfig
  - make
  artifacts:
    name: WRPC_SW_CI_%CI_JOB_ID%
    paths:
    - rt_cpu.elf
