/*
  Register definitions for slave core: WR aux sma output generation module

  * File           : sma_config_regs.h
  * Author         : auto-generated by wbgen2 from sma_config.wb
  * Created        : Thu Jun 10 16:33:07 2021
  * Standard       : ANSI C

    THIS FILE WAS GENERATED BY wbgen2 FROM SOURCE FILE sma_config.wb
    DO NOT HAND-EDIT UNLESS IT'S ABSOLUTELY NECESSARY!

*/

#ifndef __WBGEN2_REGDEFS_SMA_CONFIG_WB
#define __WBGEN2_REGDEFS_SMA_CONFIG_WB

#include <inttypes.h>

#if defined( __GNUC__)
#define PACKED __attribute__ ((packed))
#else
#error "Unsupported compiler?"
#endif

#ifndef __WBGEN2_MACROS_DEFINED__
#define __WBGEN2_MACROS_DEFINED__
#define WBGEN2_GEN_MASK(offset, size) (((1ULL<<(size))-1) << (offset))
#define WBGEN2_GEN_WRITE(value, offset, size) (((value) & ((1<<(size))-1)) << (offset))
#define WBGEN2_GEN_READ(reg, offset, size) (((reg) >> (offset)) & ((1<<(size))-1))
#define WBGEN2_SIGN_EXTEND(value, bits) (((value) & (1<<bits) ? ~((1<<(bits))-1): 0 ) | (value))
#endif


/* definitions for register: SMA0 MUX */

/* definitions for field: SMA0 Signal Selection in reg: SMA0 MUX */
#define SMA_CONFIG_SMA0_MUX_MUX_MASK           WBGEN2_GEN_MASK(0, 8)
#define SMA_CONFIG_SMA0_MUX_MUX_SHIFT          0
#define SMA_CONFIG_SMA0_MUX_MUX_W(value)       WBGEN2_GEN_WRITE(value, 0, 8)
#define SMA_CONFIG_SMA0_MUX_MUX_R(reg)         WBGEN2_GEN_READ(reg, 0, 8)

/* definitions for field: SMA0 Signal Selection readback in reg: SMA0 MUX */
#define SMA_CONFIG_SMA0_MUX_MUX_RD_MASK        WBGEN2_GEN_MASK(8, 8)
#define SMA_CONFIG_SMA0_MUX_MUX_RD_SHIFT       8
#define SMA_CONFIG_SMA0_MUX_MUX_RD_W(value)    WBGEN2_GEN_WRITE(value, 8, 8)
#define SMA_CONFIG_SMA0_MUX_MUX_RD_R(reg)      WBGEN2_GEN_READ(reg, 8, 8)

/* definitions for register: SMA1 MUX */

/* definitions for field: SMA1 Signal Selection in reg: SMA1 MUX */
#define SMA_CONFIG_SMA1_MUX_MUX_MASK           WBGEN2_GEN_MASK(0, 8)
#define SMA_CONFIG_SMA1_MUX_MUX_SHIFT          0
#define SMA_CONFIG_SMA1_MUX_MUX_W(value)       WBGEN2_GEN_WRITE(value, 0, 8)
#define SMA_CONFIG_SMA1_MUX_MUX_R(reg)         WBGEN2_GEN_READ(reg, 0, 8)

/* definitions for field: SMA1 Signal Selection readback in reg: SMA1 MUX */
#define SMA_CONFIG_SMA1_MUX_MUX_RD_MASK        WBGEN2_GEN_MASK(8, 8)
#define SMA_CONFIG_SMA1_MUX_MUX_RD_SHIFT       8
#define SMA_CONFIG_SMA1_MUX_MUX_RD_W(value)    WBGEN2_GEN_WRITE(value, 8, 8)
#define SMA_CONFIG_SMA1_MUX_MUX_RD_R(reg)      WBGEN2_GEN_READ(reg, 8, 8)

/* definitions for register: Customed Signal Period Register : High State */

/* definitions for register: Customed Signal Period Register : Low State */

/* definitions for register: Customed Signal Coarse Shift Register */

/* definitions for register: PPS Period High Register */

/* definitions for register: PPS Coarse Shift Register */

/* definitions for register: UTC Coding Coarse Shift Register */

/* definitions for register: SMA0 Fine Delays Register */

/* definitions for register: SMA1 Fine Delays Register */

PACKED struct SMA_CONFIG_WB {
  /* [0x0]: REG SMA0 MUX */
  uint32_t SMA0_MUX;
  /* [0x4]: REG SMA1 MUX */
  uint32_t SMA1_MUX;
  /* [0x8]: REG Customed Signal Period Register : High State */
  uint32_t CUS_PRH;
  /* [0xc]: REG Customed Signal Period Register : Low State */
  uint32_t CUS_PRL;
  /* [0x10]: REG Customed Signal Coarse Shift Register */
  uint32_t CUS_CSR;
  /* [0x14]: REG PPS Period High Register */
  uint32_t PPS_PRH;
  /* [0x18]: REG PPS Coarse Shift Register */
  uint32_t PPS_CSR;
  /* [0x1c]: REG UTC Coding Coarse Shift Register */
  uint32_t UTC_CSR;
  /* [0x20]: REG SMA0 Fine Delays Register */
  uint32_t SMA0_FDLY;
  /* [0x24]: REG SMA1 Fine Delays Register */
  uint32_t SMA1_FDLY;
};


#define SMA_CONFIG_PERIPH_PREFIX              "sma_config"
#define SMA_CONFIG_PERIPH_NAME                "WR aux sma output generation module"
#define SMA_CONFIG_PERIPH_DESC                WBGEN2_DESC("The module allows gerating WR-aligned signal including PPS/mPPS/")

#endif
