/*
  Register definitions for slave core: DDS/PLL Sync Pulse Generator Unit

  * File           : wb_dds_sync_unit.h
  * Author         : auto-generated by wbgen2 from dds_sync_unit_wb.wb
  * Created        : Thu Jul 25 11:31:32 2019
  * Standard       : ANSI C

    THIS FILE WAS GENERATED BY wbgen2 FROM SOURCE FILE dds_sync_unit_wb.wb
    DO NOT HAND-EDIT UNLESS IT'S ABSOLUTELY NECESSARY!

*/

#ifndef __WBGEN2_REGDEFS_DDS_SYNC_UNIT_WB_WB
#define __WBGEN2_REGDEFS_DDS_SYNC_UNIT_WB_WB

#ifdef __KERNEL__
#include <linux/types.h>
#else
#include <inttypes.h>
#endif

#if defined( __GNUC__)
#define PACKED __attribute__ ((packed))
#else
#error "Unsupported compiler?"
#endif

#ifndef __WBGEN2_MACROS_DEFINED__
#define __WBGEN2_MACROS_DEFINED__
#define WBGEN2_GEN_MASK(offset, size) (((1<<(size))-1) << (offset))
#define WBGEN2_GEN_WRITE(value, offset, size) (((value) & ((1<<(size))-1)) << (offset))
#define WBGEN2_GEN_READ(reg, offset, size) (((reg) >> (offset)) & ((1<<(size))-1))
#define WBGEN2_SIGN_EXTEND(value, bits) (((value) & (1<<bits) ? ~((1<<(bits))-1): 0 ) | (value))
#endif


/* definitions for register: Control/Status Register */

/* definitions for field: Trigger Sync Pulse 0 in reg: Control/Status Register */
#define DS_CSR_TRIG0                          WBGEN2_GEN_MASK(0, 1)

/* definitions for field: Trigger Sync Pulse 0 in reg: Control/Status Register */
#define DS_CSR_TRIG1                          WBGEN2_GEN_MASK(1, 1)

/* definitions for field: Trigger Sync Pulse 0 in reg: Control/Status Register */
#define DS_CSR_TRIG2                          WBGEN2_GEN_MASK(2, 1)

/* definitions for field: Trigger Sync Pulse 0 in reg: Control/Status Register */
#define DS_CSR_TRIG3                          WBGEN2_GEN_MASK(3, 1)

/* definitions for field: Sync Pulse Ready in reg: Control/Status Register */
#define DS_CSR_READY_MASK                     WBGEN2_GEN_MASK(4, 4)
#define DS_CSR_READY_SHIFT                    4
#define DS_CSR_READY_W(value)                 WBGEN2_GEN_WRITE(value, 4, 4)
#define DS_CSR_READY_R(reg)                   WBGEN2_GEN_READ(reg, 4, 4)

/* definitions for register: Output 0 Control */

/* definitions for field: WR PPS offset in reg: Output 0 Control */
#define DS_OCR0_PPS_OFFS_MASK                 WBGEN2_GEN_MASK(0, 4)
#define DS_OCR0_PPS_OFFS_SHIFT                0
#define DS_OCR0_PPS_OFFS_W(value)             WBGEN2_GEN_WRITE(value, 0, 4)
#define DS_OCR0_PPS_OFFS_R(reg)               WBGEN2_GEN_READ(reg, 0, 4)

/* definitions for field: Fine delay adjust in reg: Output 0 Control */
#define DS_OCR0_FINE_MASK                     WBGEN2_GEN_MASK(4, 5)
#define DS_OCR0_FINE_SHIFT                    4
#define DS_OCR0_FINE_W(value)                 WBGEN2_GEN_WRITE(value, 4, 5)
#define DS_OCR0_FINE_R(reg)                   WBGEN2_GEN_READ(reg, 4, 5)

/* definitions for field: Polarity in reg: Output 0 Control */
#define DS_OCR0_POL                           WBGEN2_GEN_MASK(9, 1)

/* definitions for field: Serdes Bitmask in reg: Output 0 Control */
#define DS_OCR0_MASK_MASK                     WBGEN2_GEN_MASK(10, 8)
#define DS_OCR0_MASK_SHIFT                    10
#define DS_OCR0_MASK_W(value)                 WBGEN2_GEN_WRITE(value, 10, 8)
#define DS_OCR0_MASK_R(reg)                   WBGEN2_GEN_READ(reg, 10, 8)

/* definitions for register: Output 1 Control */

/* definitions for field: WR PPS offset in reg: Output 1 Control */
#define DS_OCR1_PPS_OFFS_MASK                 WBGEN2_GEN_MASK(0, 4)
#define DS_OCR1_PPS_OFFS_SHIFT                0
#define DS_OCR1_PPS_OFFS_W(value)             WBGEN2_GEN_WRITE(value, 0, 4)
#define DS_OCR1_PPS_OFFS_R(reg)               WBGEN2_GEN_READ(reg, 0, 4)

/* definitions for field: Fine delay adjust in reg: Output 1 Control */
#define DS_OCR1_FINE_MASK                     WBGEN2_GEN_MASK(4, 5)
#define DS_OCR1_FINE_SHIFT                    4
#define DS_OCR1_FINE_W(value)                 WBGEN2_GEN_WRITE(value, 4, 5)
#define DS_OCR1_FINE_R(reg)                   WBGEN2_GEN_READ(reg, 4, 5)

/* definitions for field: Polarity in reg: Output 1 Control */
#define DS_OCR1_POL                           WBGEN2_GEN_MASK(9, 1)

/* definitions for field: Serdes Bitmask in reg: Output 1 Control */
#define DS_OCR1_MASK_MASK                     WBGEN2_GEN_MASK(10, 8)
#define DS_OCR1_MASK_SHIFT                    10
#define DS_OCR1_MASK_W(value)                 WBGEN2_GEN_WRITE(value, 10, 8)
#define DS_OCR1_MASK_R(reg)                   WBGEN2_GEN_READ(reg, 10, 8)

/* definitions for register: Output 2 Control */

/* definitions for field: WR PPS offset in reg: Output 2 Control */
#define DS_OCR2_PPS_OFFS_MASK                 WBGEN2_GEN_MASK(0, 4)
#define DS_OCR2_PPS_OFFS_SHIFT                0
#define DS_OCR2_PPS_OFFS_W(value)             WBGEN2_GEN_WRITE(value, 0, 4)
#define DS_OCR2_PPS_OFFS_R(reg)               WBGEN2_GEN_READ(reg, 0, 4)

/* definitions for field: Fine delay adjust in reg: Output 2 Control */
#define DS_OCR2_FINE_MASK                     WBGEN2_GEN_MASK(4, 5)
#define DS_OCR2_FINE_SHIFT                    4
#define DS_OCR2_FINE_W(value)                 WBGEN2_GEN_WRITE(value, 4, 5)
#define DS_OCR2_FINE_R(reg)                   WBGEN2_GEN_READ(reg, 4, 5)

/* definitions for field: Polarity in reg: Output 2 Control */
#define DS_OCR2_POL                           WBGEN2_GEN_MASK(9, 1)

/* definitions for field: Serdes Bitmask in reg: Output 2 Control */
#define DS_OCR2_MASK_MASK                     WBGEN2_GEN_MASK(10, 8)
#define DS_OCR2_MASK_SHIFT                    10
#define DS_OCR2_MASK_W(value)                 WBGEN2_GEN_WRITE(value, 10, 8)
#define DS_OCR2_MASK_R(reg)                   WBGEN2_GEN_READ(reg, 10, 8)

/* definitions for register: Output 3 Control */

/* definitions for field: WR PPS offset in reg: Output 3 Control */
#define DS_OCR3_PPS_OFFS_MASK                 WBGEN2_GEN_MASK(0, 4)
#define DS_OCR3_PPS_OFFS_SHIFT                0
#define DS_OCR3_PPS_OFFS_W(value)             WBGEN2_GEN_WRITE(value, 0, 4)
#define DS_OCR3_PPS_OFFS_R(reg)               WBGEN2_GEN_READ(reg, 0, 4)

/* definitions for field: Fine delay adjust in reg: Output 3 Control */
#define DS_OCR3_FINE_MASK                     WBGEN2_GEN_MASK(4, 5)
#define DS_OCR3_FINE_SHIFT                    4
#define DS_OCR3_FINE_W(value)                 WBGEN2_GEN_WRITE(value, 4, 5)
#define DS_OCR3_FINE_R(reg)                   WBGEN2_GEN_READ(reg, 4, 5)

/* definitions for field: Polarity in reg: Output 3 Control */
#define DS_OCR3_POL                           WBGEN2_GEN_MASK(9, 1)

/* definitions for field: Serdes Bitmask in reg: Output 3 Control */
#define DS_OCR3_MASK_MASK                     WBGEN2_GEN_MASK(10, 8)
#define DS_OCR3_MASK_SHIFT                    10
#define DS_OCR3_MASK_W(value)                 WBGEN2_GEN_WRITE(value, 10, 8)
#define DS_OCR3_MASK_R(reg)                   WBGEN2_GEN_READ(reg, 10, 8)
/* [0x0]: REG Control/Status Register */
#define DS_REG_CSR 0x00000000
/* [0x4]: REG Output 0 Control */
#define DS_REG_OCR0 0x00000004
/* [0x8]: REG Output 1 Control */
#define DS_REG_OCR1 0x00000008
/* [0xc]: REG Output 2 Control */
#define DS_REG_OCR2 0x0000000c
/* [0x10]: REG Output 3 Control */
#define DS_REG_OCR3 0x00000010
#endif
