#!/usr/bin/env python3

# Cheap version of wrpc-spll-plotter.py
# It takes as argument a log file containing the lines output by wrpc tool
# and parses only the lines containing the string "raw source=" which comes
# from the raw debug FIFO of the softPLL
# Very basic outlier removal, should be upgraded to be as it is on wrpc-spll-plotter.py

# How to use this script:
# First, you need to compile wrpc (softPLL) and enable raw debug FIFO for tag of desired sources
# Then, you need to compile wrpc (the tool)
# Start wrpc (tool) on the switch with the following command:
# ./wrpc spll-recorder -b wrsv4 > spll.log
# Once you got enough tags, stop wrpc (tool) using Ctrl+C
# Then, copy the log file (spll.log) on your computer
# Modify src1 and src2 variable below according to the sources you are pushing through the debug FIFO
# Start this script with log file as parameter:
# python3 spll_raw_plotter.py spll.log 

# Example of lines generated by wrpc tool:
# main phase_current=16759194 phase_target=16759194 time_ms=16289518 ref=16386 tag=16388 err=-1 sample=6955412 y=38428
# raw source=5 tag=1103288
# raw source=6 tag=1112180

import sys
from matplotlib import animation
from matplotlib import pyplot as plt
import numpy as np
import threading
import logging
import copy

# Sources to compare
# 4: main
# 5: ext (front panel)
# 6: holdover
src1 = 5
src2 = 4

data = {}
diff = []
time = []
src_name = ["", "", "", "", "main", "ext", "holdover"]

def remove_outliers(x, threshold ):
    y=copy.copy(x)
    win = 3
    for i in range(win, len(x) - win ):
        med = np.median( x[i-win:i+win+1] )
        err = np.abs (x[i] / med )
        if ( err > threshold or err < (1.0/threshold) ):
            y[i] = med
    return y
        
def acquisition(noSamples):
    lsb = 10**12 * (1 / ((62500000 - 3814) * 2**14))
    print("lsb " + str(lsb))
    logging.info("ACQ Thread: starting")
    nsamples = 0
    data[0] = []
    data[1] = []
    with open (sys.argv[1]) as recorder_op:
        for line in recorder_op:
            l = recorder_op.readline().rstrip('\n').rstrip('\r').lstrip(' ').lstrip('\t').rstrip(' ')
            if(l.find("raw source="+str(src1)) > -1):
                data[0].append(int(l.split("tag=")[1]))
            elif(l.find("raw source="+str(src2)) > -1):
                data[1].append(int(l.split("tag=")[1]))

        print("src1 ({}: {}) data len = {}".format(src1, src_name[src1], len(data[0])))
        print("src2 ({}: {}) data len = {}".format(src2, src_name[src2], len(data[1])))
        l = min(len(data[0]), len(data[1]))
        for i in range(l):
            t = data[0][i] - data[1][i]
            #print(data["ext"][i], data["holdover"][i], t)
            # basic outlier removal (when the tag counter wraps for one of the chanel)
            if abs(t) > 2**20:
                pass
                #print("removing value: {}".format(t))
            else:
                diff.append(t*lsb)
 
        print("Min: {} ps".format(min(diff)))
        print("Max: {} ps".format(max(diff)))
        print("Variation: {} ps".format(max(diff)-min(diff)))

        #remove_outliers(diff, 1.05)


def animated_refresh(ax):
    ax.clear()
    src = "A"
    signal = "B"
    lplot = len(diff)
    tm = np.linspace(0, lplot/3814, lplot)
    plt.plot(tm, diff[0:lplot])
    #plt.stairs( diff[0:lplot], label="%s:%s" % ( src, signal ) )
    plt.legend()
    plt.grid()



def main():

    acquisition(1024)
    fig, ax = plt.subplots( 1, 1 )
    animated_refresh(ax)
    plt.title("SoftPLL debug")
    plt.xlabel("Time [s]")
    plt.ylabel("Phase offset [ps]")
    plt.show()

if __name__ == "__main__":
    main()
