#!/bin/bash

# Use: ./tools/update_configs

# preserve current
T=$(mktemp /tmp/config.XXXXXX)
mv .config $T

for n in configs/*; do
    b=$(basename $n)
    echo "Updating $b"
    ./scripts/kconfig/conf --defconfig=$n $(pwd)/Kconfig | grep -v '^#'
    make -s savedefconfig
    mv defconfig $n
done

mv $T .config
